### PR TITLE
Lint updates

### PR DESCRIPTION
**Pull request by toasted-nutbread**
Addresses lint issues in #289.

The question about whether ```"arrow-parens"``` should be ```"as-needed"``` or ```"always"``` is still an open question. Once answered, I will add a commit to address whatever the preference is.

### CODE REVIEW

**Comment by FooSoft** [comment]
Very nice, thanks for the cleanup :+1:

**Comment by toasted-nutbread** [comment]
@FooSoft do you have a preference for parentheses and arrow functions? I.e. should they be mandatory (```"always"``` / ```(e) => something(e)```) or omitted when single-arg (```"as-needed"``` / ```e => something(e)```)? The former is currently the more common in the codebase.

**Comment by FooSoft** [comment]
I tend to avoid using unnecessary characters where possible (no extra parens in `if` statements for example), but also at the same time I prefer consistency (so always do curly braces, even for single line control statements), so this could go either way.

I've noticed that you do mandatory parens in your code, and you are probably right to favour consistency over brevity for this. As you mentioned, the fact that this style is adopted by Airbnb; that may very well indicate that is the more "standard" way of doing things (so we might as well make it be the standard for this codebase as well).

**Comment by toasted-nutbread** [comment]
> I've noticed that you do mandatory parens in your code, and you are probably right to favour consistency over brevity for this.

I don't think I followed a consistent pattern in all of the code I've wrote. Sometimes I followed the existing ```e => something(e)```, but other times I didn't. I do default to parens, but if there is a reference in close proximity which was using no-parens, I dropped them. Since there wasn't a lint file previously, I didn't have anything to go by.

**Pull request merged**
