### PR TITLE
Settings profiles

### PR DESCRIPTION
**Pull request by toasted-nutbread**
This change adds support for multiple profiles; the diff should be a bit more straightforward since all of the prerequisites were taken care of in #204, #205.

### CODE REVIEW

**Comment by odehjoseph** [comment]
how would you use this to separate settings for different popups? Experimenting with this and I haven't had any luck figuring it out for that purpose.

**Comment by toasted-nutbread** [comment]
> how would you use this to separate settings for different popups? Experimenting with this and I haven't had any luck figuring it out for that purpose.

This feature is the first step towards that end. There will be another feature added after this is ready which will allow you to assign conditions to profiles. These conditions will be the rules which determine how different profiles can be automatically selected based on different contexts, e.g. based on popup level or URL.

**Comment by toasted-nutbread** [comment]
My comment from #213 about isolating objects has been addressed with 9fb89d8f7d77dd70b2493f730d8b224c994a6e98.

**Comment by FooSoft** [comment]
Good work :+1:

**Pull request merged**
