### PR TITLE
get all matching profiles

### PR DESCRIPTION
**Pull request by siikamiika**
This doesn't change anything yet, but allows getting a list of matching profiles that can be used to cycle between profiles with a hotkey or a button later.

### CODE REVIEW

**Comment by toasted-nutbread** [comment]
Should any of these functions be marked as private?

**Comment by siikamiika** [comment]
I'm not sure about all of them yet, and maybe even the async version could be dropped (https://github.com/FooSoft/yomichan/issues/356). At least the generator is only used privately.

This is groundwork for a solution to issues like https://github.com/FooSoft/yomichan/issues/378 and https://github.com/FooSoft/yomichan/issues/379, but it's not the only possible way to go. Another one would be to add a global setting (such as a string) that can be used as a profile condition and switched from `browser_action`, hotkeys or a button inside the popup.

The advantage with this approach is that you can always have profiles with duplicate conditions and the one sorted first (as far as I understand profiles) will always be used, but now you could see all of them. The disadvantage is that the profile switch is not persistent, but I'd imagine that an easy workaround would be rearranging the profiles.

Yet another issue to solve before live profile switching can be implemented is properly applying all settings to the popup when the profile changes. Full refresh could be one solution.

**Comment by toasted-nutbread** [comment]
> I'm not sure about all of them yet, and maybe even the async version could be dropped (#356).

This might be doable; I would be sure to test if there are any obvious errors that occur during startup for example (reload the extension). I know some can already occur if content pages are trying to use the background APIs but the background isn't fully initialized yet, but that's more of a separate issue.

> At least the generator is only used privately.

Just mark anything that isn't intended to be used externally with `_`.

**Comment by siikamiika** [comment]
Closing this PR because I'm working on another branch that includes something similar. I stopped working on it for now because I realized that I need reliable communication from `DisplayFloat` to `Frontend` to be able to set the selected profile in both. I'll explore the peer-to-peer option with logic similar to what's done with the `Yomichan` class in https://github.com/FooSoft/yomichan/pull/386 instead of storing everything in Backend. https://github.com/FooSoft/yomichan/issues/368

https://github.com/siikamiika/yomichan/tree/switch-matching-profiles

**Pull request closed without merging**
