### PR TITLE
popup proxy for iframe

### PR DESCRIPTION
**Pull request by siikamiika**
My plan is to empirically detect the position of iframes on the page to position the popup. It probably won't be perfect, but a lot better than the current iframe support. If I can't get it to work, I'll make it fallback to full width popups.

Opening the PR to get comments on the general structure of this solution, but don't spend too much time reviewing the code yet.

### CODE REVIEW

**Comment by toasted-nutbread** [comment]
For reference, here is some code that I worked on:

https://github.com/toasted-nutbread/yomichan/tree/iframe-popups

Also, see this specific comment: https://github.com/FooSoft/yomichan/issues/29#issuecomment-568207279, which is a race issue with frame load order. I primarily notice it in Chrome.

**Comment by siikamiika** [comment]
Thanks, seems like the general direction is about the same, but you reused `PopupProxy`. I'll see if I can do something about the race issue. Do you know if it's related to why on some pages the iframes don't work at all?

**Comment by toasted-nutbread** [comment]
I have personally not seen those cases, so I'm not sure. Nothing immediately strikes me as to why that would currently happen. The reason the race condition is an issue for the way I set up the iframe branch is because the iframe tries to communicate with the root frame (id 0), but it sends the message before the root frame has set up the listener.

**Comment by siikamiika** [comment]
> I have personally not seen those cases, so I'm not sure.

Try on [this Amazon page](https://www.amazon.co.jp/%E6%96%B0%E4%B8%96%E7%95%8C%E3%82%88%E3%82%8A-%E4%B8%8A-%E8%AC%9B%E8%AB%87%E7%A4%BE%E6%96%87%E5%BA%AB-%E8%B2%B4%E5%BF%97%E7%A5%90%E4%BB%8B-ebook/dp/B009GXME5G/) from #29 (with a version before #357). It works on Firefox for me, but not on Chrome. The twitter widget [here](https://dic.nicovideo.jp/) fails on both browsers.

**Comment by toasted-nutbread** [comment]
The twitter one probably doesn't work because there are some about:blank shenanigans going on, and Yomichan doesn't run on about:blank. We will have to add [`"match_about_blank": true`](https://developer.chrome.com/extensions/content_scripts) to support this.

**Comment by siikamiika** [comment]
> The twitter one probably doesn't work because there are some about:blank shenanigans going on, and Yomichan doesn't run on about:blank. We will have to add [`"match_about_blank": true`](https://developer.chrome.com/extensions/content_scripts) to support this.

Wow, nice find! This actually fixes both of the sites on Chrome and Firefox.

I've added a guessing framework which seems to work fine as long as there aren't nested iframes. I'll probably make it fall back to full width popup.

**Comment by siikamiika** [comment]
This changes current behavior: https://github.com/FooSoft/yomichan/pull/364/commits/d6ba291d0ce341fa570b73499ea90603fc449906
The popup size won't be kept after scanning again.

**Comment by siikamiika** [comment]
@toasted-nutbread Are there any considerations such as permissions for adding `match_about_blank`? You can push it to master if you want.

**Comment by toasted-nutbread** [comment]
> @toasted-nutbread Are there any considerations such as permissions for adding `match_about_blank`? You can push it to master if you want.

I'll check and see if it reports any permissions differences on install, but I don't think it does. Other than that, I don't think there should be any issues. I'll do a little bit of testing to confirm and add it in, I'm working on something in that area anyway.

**Comment by toasted-nutbread** [comment]
Didn't notice any differences in the permissions pages or popups during installation. f0bd61617785e503ffd0649ae60502469eb75876

**Pull request closed without merging**
