### PR TITLE
Lookup wildcards

### PR DESCRIPTION
**Pull request by toasted-nutbread**
Adds support for suffix wildcards on the search page. This adds partial support for #128.

Tracked in #270.

---

image

### CODE REVIEW

**Comment by siikamiika** [comment]
Maybe `findTermsWildcard` should use a new database method that has a limit, and skip sorting altogether to enable pagination

**Comment by toasted-nutbread** [comment]
I think imposing a limit of the number of results returned from the search is probably a good idea, especially with how many results can be returned using the ```getAll``` methods. Pagination presents an issue in that you can't really give the indexedDB API a cursor to start searching at. Might be best done as something like "Show more results" instead of something like Page 1, 2, 3, etc. I'll if this works well.

**Comment by siikamiika** [comment]
I was thinking that you could give a new lower and upper bound when going to the next page. For example:
- Look up `あ＊` (`IDBKeyRange.bound('あ', 'あ\uffff')`)
- while `options.general.maxResults` hasn't been reached:
  - Fetch the first `options.general.maxResults * dictionary count etc.` results
  - Process the results based on split/group/merge settings and do additional exact DB searches if needed
  - Store the word (for example あか) that made the amount of results reach `options.general.maxResults` and `break`
- Show results along with a button that does `IDBKeyRange.bound('あか', 'あか\uffff')` but skips the words that were the immediate results (not merge results) on the previous pages

Going back is probably too hard to do in the DB unless you cache the pages. I agree that it would also be difficult to count the amount of pages there will be unless you fake it and don't show the number of the last page.

**Comment by FooSoft** [comment]
Looks good to me :+1:

**Comment by toasted-nutbread** [comment]
So a bit of a follow up to @siikamiika's comments: I haven't completely tested everything, but I think some of the asks would involve significant changes to the code, potentially adding complexity. A few factors below:

* Supporting all three values for ```resultOutputMode``` (```'group', 'merge', 'split'```) for wildcards, some of which do their own sorting/grouping.
* The usage of ```dictTermsUndupe```, which operate on the full set of results.
* ```options.general.maxResults * dictionary count``` is not necessarily accurate, especially with frequency dictionaries. This is compounded by how the lookup has to do 2x the searches: one using reading, and one using expression.

Another thing I noticed: It is possible to sort the results by ordering by the expression/reading string. However, the current method may sort the more "relevant" results first. For example, searching ```aga*``` using the current method yields ```上がる```,  but when sorting using the string, the first result is ```あがぁな```. Not only is the latter potentially less interesting, jisho.org also yields [```上がる```as the first resul](https://jisho.org/search/aga*)t. So while the results aren't identical, it shows that a similar search on a dictionary website doesn't sort results in string-sort order.

**Pull request merged**
