### PR TITLE
Add missing sequence and sequenceDictionary Info for termGrouped

### PR DESCRIPTION
**Pull request by qharscoet**
Added sequence info for groupedSequence, as #1591 added it in merged but not Grouped.

Also updated test data

### CODE REVIEW

**Comment by toasted-nutbread** [comment]
I think the reason why the fields were empty for grouped mode is because the sequence is not used for merging, and specifying a single `sequence`/`sequenceDictionary` is misleading, since the entries may be coming from different dictionaries and/or have multiple `sequence` IDs.

Based on the changes here, only the `sequence`/`sequenceDictionary` that is encountered first would be exposed.

I assume this is to address more compatibility issues mentioned in https://github.com/FooSoft/yomichan/issues/1580#issuecomment-812904279?

**Comment by qharscoet** [comment]
Hmm, in that case couldn't we still expose the sequence in the `defintions` array and keep -1 in the root ?

Yes, grouped mode is the mode I use myself to make my anki cards and I'd like to keep this functionality as it was present prior to the March update 😅

Maybe I'll switch to merged mode then, but I'd like to keep only the reading I encounter instead of having them all in the same card.

**Comment by toasted-nutbread** [comment]
Yeah, adding the sequence to the definitions makes sense. The reason I didn't originally do that was because I didn't think anyone used that for Anki data, so I omitted it.

Check out #1617, that PR should fix the issues. I may also consider a follow-up PR which removes the `sequence` field from the internal data format and derive it for the Anki template renderer data format, since it's slightly redundant.

And since you're the first person in a while to open a PR (besides myself), let me know if you noticed anything in the codebase that would have made it easier to understand or figure out where/how to make changes; I know a lot of stuff isn't really documented. Appreciate the contribution

**Comment by qharscoet** [comment]
> The reason I didn't originally do that was because I didn't think anyone used that for Anki data, so I omitted it.

Yeah it's just so that I can use a link in my cards to pull up more info about the words and the kanjis used in the Kanji Study app while reviewing on Android. Kind of specific but maybe someone else could use this info.

> And since you're the first person in a while to open a PR (besides myself), let me know if you noticed anything in the codebase that would have made it easier to understand or figure out where/how to make changes; I know a lot of stuff isn't really documented. Appreciate the contribution

I mostly looked at what you edited to know where to look at, so I can't really speak about the general organization of the code.
First thing that comes to mind from what I saw is in the name of the variables, things like `dictionaryEntries2` in `_groupDictionaryEntriesByHeadword` that is named `groups` in `_getRelatedDictionaryEntries` , stuff like that.

```javascript  
const newDictionaryEntries = [];
for (const group of groupedDictionaryEntries) {
    newDictionaryEntries.push(this._createGroupedDictionaryEntry(group.dictionaryEntries, group.sequence, group.sequenceDictionary, true));
}
```

```javascript
const results = [];
for (const dictionaryEntries2 of groups.values()) {
    const dictionaryEntry = this._createGroupedDictionaryEntry(dictionaryEntries2.entries, dictionaryEntries2.sequence, dictionaryEntries2.sequenceDictionary, false);
    results.push(dictionaryEntry);
}
```

**Comment by toasted-nutbread** [comment]
Thanks for the feedback, I'll make a PR to improve the consistency of those two cases also.

**Pull request closed without merging**
