### PR TITLE
fix custom anki templates

### PR DESCRIPTION
**Pull request by siikamiika**
Fixes https://github.com/FooSoft/yomichan/issues/473
Broken in https://github.com/FooSoft/yomichan/pull/380

### CODE REVIEW

**Comment by siikamiika** [comment]
@FooSoft I think there could be a hotfix for this, but I'm not sure if the other stuff merged after the current release is stable enough to be included with the hotfix (there's a database upgrade among other things). Do you have any ideas how to proceed?

**Comment by toasted-nutbread** [comment]
Hotfix branch off of the latest stable + cherry pick would be my suggestion. Using a ".1" on the end to indicate the hotfix was I think the pattern from #304.

**Comment by siikamiika** [comment]
I've pushed the hotfix release to https://github.com/FooSoft/yomichan/tree/hotfix-custom-anki-templates. Not sure what would happen if I released it to GitHub.

**Comment by FooSoft** [comment]
Cool! We get to finally use the hotfix field in the version :tada: 

I'll queue up a submission for the branch @siikamiika created, unfortunately it will take a couple of days to get it listed for Chrome (fortunately, Firefox has faster approval process).

**Comment by FooSoft** [comment]
Submission queued up. I think it already went through for Firefox, actually.

**Comment by siikamiika** [comment]
@FooSoft Thanks!

**Comment by zdzislaw-s** [comment]
:100: :clap:

**Pull request merged**
